const names = [
    'John Smith',
    'Emma Johnson',
    'James Williams',
    'Olivia Brown',
    'Liam Jones',
    'Sophia Garcia',
    'Noah Miller',
    'Ava Davis',
    'Mason Martinez',
    'Isabella Hernandez',
    'Ethan Moore',
    'Mia Taylor',
    'Lucas Anderson',
    'Harper Thomas',
    'Logan Jackson',
    'Amelia White',
    'Jackson Harris',
    'Charlotte Martin',
    'Aiden Thompson',
    'Evelyn Martinez',
    'Sebastian Lewis',
    'Abigail Walker',
    'Levi Young',
    'Emily Hall',
    'Benjamin Allen',
    'Aria King',
    'Elijah Wright',
    'Scarlett Scott',
    'Daniel Green',
    'Victoria Adams',
    'Matthew Baker',
    'Grace Gonzalez',
    'Henry Nelson',
    'Zoey Hill',
    'Owen Cooper',
    'Layla Carter',
    'Wyatt Ramirez',
    'Nathan Perez',
    'Chloe Roberts',
    'Jack Turner',
    'Lily Phillips',
    'Caleb Campbell',
    'Hannah Parker',
    'Samuel Evans',
    'Sofia Edwards',
    'David Collins',
    'Riley Stewart',
    'Carter Rogers',
    'Bella Reed',
    'Gabriel Cook',
    'Ella Morgan'
  ];
  

export function getRandomName(): string {
    const randomIndex = Math.floor(Math.random() * names.length);
    return names[randomIndex];
  }  